channels:
  - districtdatalabs
  - pyviz
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - _py-xgboost-mutex
  - alabaster
  - argh
  - astroid
  - atomicwrites
  - attrs
  - autopep8
  - babel
  - backcall
  - black
  - bleach
  - bokeh
  - ca-certificates
  - certifi
  - cffi
  - chardet
  - cloudpickle
  - coverage
  - cryptography
  - cycler
  - dbus
  - deap
  - decorator
  - defusedxml
  - diff-match-patch
  - docutils
  - entrypoints
  - expat
  - fancycompleter
  - fastcache
  - flake8
  - fontconfig
  - freetype
  - future
  - gettext
  - glib
  - gmp
  - gmpy2
  - gst-plugins-base
  - gstreamer
  - holoviews
  - icu
  - idna
  - imagesize
  - importlib_metadata
  - inflection
  - intervaltree
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - isort
  - jedi
  - jeepney
  - jinja2
  - joblib
  - jpeg
  - json5
  - jsonschema
  - jupyter_client
  - jupyter_contrib_core
  - jupyter_contrib_nbextensions
  - jupyter_core
  - jupyter_highlight_selected_word
  - jupyter_latex_envs
  - jupyter_nbextensions_configurator
  - jupyterlab
  - jupyterlab_server
  - jupytext
  - keyring
  - kiwisolver
  - lazy-object-proxy
  - ld_impl_linux-64
  - libblas
  - libcblas
  - libclang
  - libffi
  - libgcc-ng
  - libgfortran-ng
  - libgomp
  - libiconv
  - liblapack
  - libllvm9
  - libopenblas
  - libpng
  - libsodium
  - libspatialindex
  - libstdcxx-ng
  - libtiff
  - libuuid
  - libuv
  - libxcb
  - libxgboost
  - libxkbcommon
  - libxml2
  - libxslt
  - lxml
  - lz4-c
  - markupsafe
  - matplotlib
  - matplotlib-base
  - mccabe
  - mistune
  - more-itertools
  - mpc
  - mpfr
  - mpmath
  - nbconvert
  - nbformat
  - ncurses
  - nodejs
  - nose
  - notebook
  - nspr
  - nss
  - numpy
  - numpydoc
  - olefile
  - openssl
  - packaging
  - pandas
  - pandas-datareader
  - pandoc
  - pandocfilters
  - param
  - parso
  - pathtools
  - patsy
  - pcre
  - pdbpp
  - pexpect
  - pickleshare
  - pillow
  - pip
  - pluggy
  - prometheus_client
  - prompt-toolkit
  - prompt_toolkit
  - psutil
  - pthread-stubs
  - ptyprocess
  - py
  - py-xgboost
  - pycodestyle
  - pycparser
  - pydocstyle
  - pyflakes
  - pygments
  - pylint
  - pyopenssl
  - pyparsing
  - pyqt
  - pyrsistent
  - pysocks
  - pytest
  - pytest-cov
  - pytest-runner
  - python=3.7
  - python-dateutil
  - python-jsonrpc-server
  - python-language-server
  - python_abi
  - pytz
  - pyviz_comms
  - pyxdg
  - pyyaml
  - pyzmq
  - qdarkstyle
  - qt
  - qtawesome
  - qtconsole
  - qtpy
  - quandl
  - readline
  - requests
  - requests-cache
  - rope
  - rtree
  - scikit-learn
  - scipy
  - seaborn
  - secretstorage
  - send2trash
  - setuptools
  - six
  - snowballstemmer
  - sortedcontainers
  - sphinx
  - sphinxcontrib-applehelp
  - sphinxcontrib-devhelp
  - sphinxcontrib-htmlhelp
  - sphinxcontrib-jsmath
  - sphinxcontrib-qthelp
  - sphinxcontrib-serializinghtml
  - spyder
  - spyder-kernels
  - sqlite
  - statsmodels
  - stopit
  - sympy
  - terminado
  - testpath
  - tk
  - tornado
  - tpot
  - tqdm
  - traitlets
  - typed-ast
  - typing_extensions
  - ujson
  - update_checker
  - urllib3
  - watchdog
  - wcwidth
  - webencodings
  - wheel
  - widgetsnbextension
  - wmctrl
  - wrapt
  - wurlitzer
  - xgboost
  - xorg-libxau
  - xorg-libxdmcp
  - xz
  - yaml
  - yapf
  - yellowbrick
  - zeromq
  - zipp
  - zlib
  - zstd
  - pip:
    - beautifulsoup4
    - ipytest
    - ipython-beautifulsoup
    - pyqt5-sip
    - pyqtwebengine
    - soupsieve
    - wikipedia

