channels:
  - conda-forge
  - defaults
dependencies:
  - readline
  - python=3.7
  - pip
  - numpy
  - pandas
  - pytest
  - sympy
  - jupyterlab
  - pdbpp
  - pytest-cov
  - matplotlib
  - scipy
  - statsmodels
  - seaborn
  - yellowbrick
  - tpot
  - xgboost
  - ipywidgets
  - nose
  - quandl
  - pandas-datareader
  - spyder
  - jupyter_contrib_nbextensions
  - nodejs
  - requests-cache
  - jupytext
  - holoviews
  - bokeh

# Note that pip packages and all conda channels (?) are not listed in this file
