default: download

download:
	wget --continue https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css
	wget --continue https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css
